import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  background: {
    backgroundColor: '#FFF',
    flex: 1,
    paddingBottom: 0,
  },
  upperContainer: {
    backgroundColor: "#ffffff",
    paddingBottom: 24,
  },
  lowerContainer: {
    backgroundColor: "#e5f2ff",
    flex: 1,
    paddingTop: 16,
    minHeight: 400,
  },
  headerSection: {
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 30,
    paddingBottom: 20,
  },
  backIcon: {},
  headerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: "bold",
    color: "#0158ab",
    textAlign: "left",
    marginLeft: 20,
  },
  sectionTitle: {
    color: "#182d38",
    fontSize: 16,
    fontWeight: "bold",
    marginHorizontal: 25,
    marginBottom: 8,
  },
  sourceAccountBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dee4f6",
    padding: 14,
    marginHorizontal: 25,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  accountText: {
    color: "#0158ab",
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 8,
  },
  balanceText: {
    color: "#182d38",
    fontSize: 17,
    fontWeight: "600",
  },
  dropdownIcon: {
    position: "absolute",
    right: 14,
    top: 28,
  },
  transferBox: {
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dee4f6",
    padding: 9,
    marginHorizontal: 25,
    marginBottom: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  bankSection: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    height: 55,
    paddingVertical: 8,
  },
  bankIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    marginRight: 12,
    borderWidth: 0.4,
    borderColor: "#dee4f6",
  },
  bankSelector: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  bankText: {
    color: "#182d38",
    fontSize: 16,
    fontWeight: "500",
  },
  bankDropdownIcon: {
    marginRight: 0,
  },
  dashedLine: {
    borderBottomWidth: 1,
    borderColor: "#dee4f6",
    borderStyle: "solid",
    marginBottom: 0,
  },
  accountInputSection: {
    flexDirection: "row",
    alignItems: "center",
    paddingTop: 5,
    height: 55,
    paddingVertical: 8,
  },
  accountInput: {
    flex: 1,
    fontSize: 16,
    color: "#182d38",
    paddingVertical: 5,
    fontWeight: "500",
  },
  contactIcon: {
    marginTop: 4,
    width: 50,
    height: 50
  },
  inputWrapper: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  recipientContainer: {
    backgroundColor: "#e5f2ff",
    borderTopWidth: 0,
    borderColor: "#dee4f6",
    borderRadius: 4,
    marginHorizontal: 25,
    marginTop: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
    height: 48, // Fixed height to match placeholder
  },
  recipientPlaceholder: {
    height: 48, // Matches recipientContainer height
    marginHorizontal: 25,
    marginTop: 0,
  },
  recipientNameSection: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 9,
  },
  recipientNameText: {
    color: "#182d38",
    fontSize: 16,
    fontWeight: "500",
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#266fb6",
    borderRadius: 30,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  saveButtonText: {
    color: "#266fb6",
    fontSize: 14,
    fontWeight: "600",
    marginRight: 4,
  },
  amountSection: {
    backgroundColor: "#ffffff",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dee4f6",
    height: 64,
    padding: 9,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 25,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  amountInput: {
    color: "#0158ab",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    paddingRight: 4,
  },
  vndText: {
    color: "#182d38",
    fontSize: 12, // 3/5 of amountInput fontSize
    fontWeight: "600",
    alignSelf: "center",
  },
  amountClearIconContainer: {
    backgroundColor: "#999",
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    right: 10,
  },
  contentInputContainer: {
    height: 70,
    backgroundColor: "#FFFFFF",
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#dee4f6",
    padding: 12,
    marginHorizontal: 25,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 3,
  },
  contentLabel: {
    color: "#0158ab",
    fontSize: 12,
    fontWeight: "bold",
  },
  contentInputRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  contentInput: {
    marginLeft: -4,
    fontSize: 18,
    color: "#252836",
    paddingVertical: 7,
    fontWeight: "500",
  },
  contentClearIconContainer: {
    backgroundColor: "#999",
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 32,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 14,
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
  },
  backButton: {
    height: 46,
    left: 10,
    backgroundColor: "#e5f2ff",
    borderWidth: 2,
    borderColor: "#266fb6",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 18,
    flex: 0.62,
    marginRight: 24,
    alignItems: "center",
  },
  backButtonText: {
    color: "#266fb6",
    fontSize: 15,
    fontWeight: "600",
  },
  continueButton: {
    backgroundColor: "#035aa7",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 42,
    flex: 1.4,
    alignItems: "center",
  },
  continueButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
});