import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f8fe',
  },
  header: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 30,
    paddingBottom: 20,
    marginBottom: 10,
    borderBottomWidth: 0.2,
    borderColor: '#d9def2',
    shadowColor: 'gray',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 1,
    shadowRadius: 4,
    width: '100%',
  },
  backIcon: {
    width: 32,
    height: 32,
    marginRight: 10,
    
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#29557c',
    textAlign: 'left',
   marginBottom: 8,
  },
  orderNumber: {
    fontSize: 16,
    color: '#444444',
    position: 'absolute',
    right: 0,
  },
  contentContainer: {
    paddingHorizontal: 20, // Applied padding to content container
  },
  transactionCard: {
    backgroundColor: '#f9f8fe',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#d9def2',
    padding: 12,
    marginBottom: 12,
    minHeight: 460,
  },
  transactionBlock: {
    marginBottom: 0,
    borderBottomWidth: 1,
    borderColor: '#d9def2'
  },
  title: {
    fontSize: 16,
    color: '#888888',
  },
  amount: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#0753a0',
    marginBottom: 4,
  },
  subLabel: {
    fontSize: 16,
    color: '#888888',
    marginBottom: 12,
  },
  infoBlock: {
    marginBottom: 12,
  },
   infoBlock1: {
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#d9def2',
  },
 
  infoBlock2: {
    marginBottom: 12,
  },
  infoRow3: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 8,
  },
  infoRow: {
    flexDirection: 'column',
    marginTop: 8,
  },
  infoRow1: {
    flexDirection: 'column',
    marginTop: 8,
    marginBottom: 20,
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -10,
  },
  infoContainer1: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: -10,
  },
  bankIcon: {
    width: 40,
    height: 60,
    borderRadius: 20,
    marginRight: 12,
  },
  personLabel: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#888888',
    marginBottom: 16,
  },
   personLabel1: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#888888',
    marginBottom: 16,
  },
  infoText: {
    fontSize: 16,
    color: '#888888',
  },
   infoText1: {
    fontSize: 16,
    color: '#888888',
  },
  infoTextBold: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1b313e',
    marginBottom: 4,
  },
  infoTextBold1: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1b313e',
    marginBottom: 4,
  },
  bankNameText: {
    fontSize: 16,
    color: '#888888',
    flexWrap: 'wrap',
    minHeight: 40,
    maxWidth: 280,
  },
   bankNameText1: {
    fontSize: 16,
    color: '#888888',
    flexWrap: 'wrap',
    minHeight: 40,
    maxWidth: 280,
  },
  transferContentText: {
    fontSize: 16,
    color: '#1b313e',
    fontWeight: 'bold',
    textAlign: 'right',
    flex: 1,
    flexWrap: 'wrap',
    minHeight: 40,

  },
  label: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#888888',
  },
  infoTextRight: {
    fontSize: 16,
    color: '#1b313e',
    fontWeight: 'bold',
    textAlign: 'right',
    flex: 1,
    flexWrap: 'wrap',
  },
  warningBox: {
    flexDirection: 'row',
    backgroundColor: '#FFF8E1',
    borderWidth: 1,
    borderColor: '#f9e8c5',
    borderRadius: 4,
    padding: 12,
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  warningIcon: {
    width: 24,
    height: 24,
    marginRight: 12,
    marginTop: 4,
  },
  warningText: {
    fontSize: 12,
    color: '#1b313e',
    flex: 1,
   
  },
   buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 100,
    gap : 20,
  },
  backButton: {
    height: 46,
    backgroundColor: "#e5f2ff",
    borderWidth: 1,
    borderColor: "#266fb6",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 6,
    flex: 0.4,
    alignItems: "center",
  },
  backButtonText: {
    color: "#266fb6",
    fontSize: 15,
    fontWeight: "600",
  },
  confirmButton: {
    backgroundColor: "#035aa7",
    borderRadius: 30,
    paddingVertical: 12,
    paddingHorizontal: 42,
    flex: 1,
    alignItems: "center",
  },
  confirmButtonText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "600",
  },
  modalBackground: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#f9f8fe',
    padding: 24,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
  },
  dragIndicator: {
    width: 60,
    height: 6,
    backgroundColor: '#E0E0E0',
    borderRadius: 6,
    alignSelf: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#001CFF',
    textAlign: 'center',
    marginBottom: 16,
  },
  modalDescription: {
    fontSize: 18,
    color: '#757575',
    textAlign: 'center',
    marginBottom: 24,
  },
  pinInputContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '80%',
    alignSelf: 'center',
    marginBottom: 24,
  },
  pinInput: {
    width: 48,
    height: 48,
    borderWidth: 1.5,
    borderColor: '#001CFF',
    textAlign: 'center',
    fontSize: 20,
    borderRadius: 10,
  },
  resetButton: {
    marginTop: 16,
    alignSelf: 'center',
  },
  resetButtonText: {
    fontSize: 18,
    color: '#001CFF',
  },
  otpLabel: {
    fontSize: 18,
    color: '#757575',
    marginBottom: 10,
  },
  otpCode: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#001CFF',
    marginBottom: 10,
    textAlign: 'center',
  },
  otpTimer: {
    fontSize: 18,
    color: '#001CFF',
    marginBottom: 16,
    textAlign: 'center',
  },
  autoFillText: {
    fontSize: 16,
    color: '#757575',
    textAlign: 'center',
    marginBottom: 24,
  },
  hiddenInput: {
    position: 'absolute',
    top: 0,
    left: 0,
    opacity: 0,
    width: 1,
    height: 1,
  },
  pinCircle: {
    width: 40,
    height: 40,
    borderWidth: 2,
    borderColor: '#001CFF',
    borderRadius: 20,
    backgroundColor: '#f9f8fe',
    textAlign: 'center',
    marginHorizontal: 5,
    fontSize: 20,
    color: '#000',
  },
  pinCircleFilled: {
    backgroundColor: '#001CFF',
  },
});

export default styles;