import { StyleSheet, Dimensions } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  // LoginScreen and MainScreen Styles
  background: {
    flex: 1,
    resizeMode: "cover",
  },
  safeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    justifyContent: "space-between",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingTop: 20,
  },
  logoContainer: {
    marginTop: 28,
    flexDirection: "row",
    marginLeft: -48,
  },
  logoStar: {
    width: 250,
    height: 50,
  },
  logoImage: {
    width: "130%",
    height: "130%",
    objectFit: "contain",
  },
  headerIcons: {
    alignItems: "flex-end",
    gap: 6,
    marginRight: 22,
    marginTop: 32,
  },
  iconButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderColor: "rgba(255, 255, 255, 0.3)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  iconImage: {
    width: "100%",
    height: "100%",
  },
  loginCardContainer: {
    marginTop: 60,
    paddingHorizontal: 22,
  },
  loginCard: {
    backgroundColor: "rgba(100, 100, 100, 0.3)",
    borderRadius: 20,
    padding: 24,
    paddingBottom: 0,
  },
  shieldContainer: {
    marginBottom: 16,
  },
  shieldIcon: {
    position: "relative",
    alignSelf: "flex-start",
    marginTop: 4,
    marginLeft: 6,
    marginBottom: 4,
  },
  shieldIconImage: {
    width: 28,
    height: 28,
  },
  greetingText: {
    fontSize: 18,
    color: "#FFF",
    marginBottom: 8,
    marginLeft: 4,
    fontWeight: "400",
    fontFamily: "Inter_18pt-Regular",
  },
  usernameContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.5)",
    marginBottom: 20,
  },
  usernameInput: {
    fontSize: 16,
    color: "#FFF",
    paddingVertical: 12,
    paddingHorizontal: 0,
  },
  passwordContainer: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.2)",
    marginBottom: 14,
    marginLeft: 2,
  },
  passwordInput: {
    fontSize: 18,
    color: "#FFF",
    paddingVertical: 12,
  },
  actionLinksContainer: {
    marginLeft: 4,
    flexDirection: "row",
    gap: 84,
  },
  actionLink: {
    marginTop: 3,
    fontWeight: "bold",
    color: "#FFF",
    fontSize: 16,
    opacity: 0.7,
    fontFamily: "Inter_18pt-Bold",
  },
  loginButton: {
    backgroundColor: "#6d7a88",
    borderRadius: 0,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 25,
    marginHorizontal: -24,
  },
  loginButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Inter_18pt-SemiBold",
  },
  userNameRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 14,
    marginLeft: 4,
  },
  userNameContainer: {
    flex: 1,
  },
  userName: {
    fontSize: 40,
    color: "#FFF",
    fontWeight: "light",
    lineHeight: 46,
    fontFamily: "Inter_28pt-Light",
  },
  faceIdButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 32,
    marginRight: 6,
  },
  featuresContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 70,
    paddingHorizontal: 16,
  },
  featureButton: {
    alignItems: "center",
    width: 128,
  },
  featureText: {
    color: "rgba(255, 255, 255, 0.7)",
    fontSize: 12,
    marginTop: 6,
    textAlign: "center",
    fontWeight: "400",
    fontFamily: "Inter_18pt-Regular",
  },
  featureIconImage: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  footer: {
    alignItems: "center",
    paddingBottom: 20,
    paddingHorizontal: 16,
  },
  footerArrow: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255, 255, 255, 0.0)",
    justifyContent: "center",
    alignItems: "center",
  },
  // Header (One) Styles
  headerOneContainer: {},
  headerOne: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  logomb: {
    width: 152,
    height: 70,
  },
  headerOneIcons: {
    marginRight: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  headerOneIcon: {
    marginTop: 20,
    backgroundColor: '#3a3e49',
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  logoImage1: {
    width: '100%',
    height: '100%',
  },
  // BannerSection Styles
  bannerSectionContainer: {
    paddingBottom: 10,
  },
  bannerSection: {
    marginTop: 30,
    paddingBottom: 10,
    borderWidth: 0.1,
  },
  bannerSlider: {},
  bannerContentContainer: {
    alignItems: "center",
  },
  bannerItem: {
    marginRight: 15,
  },
  bannerImage: {
    width: SCREEN_WIDTH * 0.7,
    height: 160,
    borderRadius: 15,
    borderWidth: 0.2,
  },
  // ScrollContent Styles
  scrollContent: {},
  loadingArea: {
    position: "absolute",
    top: 90,
    left: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  balanceSectionContainer: {},
  balanceSection: {
    marginTop: 0,
  },
  balanceContainer: {
    flexDirection: "row",
    paddingTop: 12,
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  userContainer: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 10,
    marginLeft: 12,
    marginRight: 10,
  },
  avatar: {
    marginTop: 12,
    width: 60,
    height: 60,
    overflow: "hidden", // Ensures the avatar image is clipped to a circle
    position: "relative", // Allows absolute positioning of the shield
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 30,
    borderWidth: 0.8,
    borderColor: 'gray'
  },
  loadingText: {},
  shieldImage: {
    width: 20, // Adjust size as needed
    height: 20, // Adjust size as needed
    position: "absolute",
    top: 0, // Positions shield slightly above the top-left corner
    left: 0, // Positions shield slightly to the left
    zIndex: 1, // Ensures shield appears above the avatar
  },
  upgradeImage: {
    width: 90,
    marginTop: 6,
    height: 34,
  },
  balanceInfoContainer: {
    marginTop: 20,
    marginBottom: 6,
    marginRight: 22,
    borderWidth: 0.5,
    flex: 1,
    backgroundColor: "rgba(36, 43, 43, 0.5)",
    padding: 10,
    borderRadius: 12,
  },
  balanceRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  balanceTitle: {
    color: "#FFF",
    fontSize: 14,
    fontWeight: "500",
    fontFamily: "Inter_18pt-Medium",
  },
  eyeButton: {
    padding: 5,
  },
  balanceAmount: {
    marginTop: 12,
    marginLeft: 2,
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Inter_18pt-Bold",
  },
  balanceCurrency: {
    marginTop: 12,
    marginLeft: 4,
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: "Inter_18pt-Bold",
  },
  arrowButton: {
    padding: 5,
    marginLeft: -40,
  },
  whiteContainer: {
    borderRadius: 23,
    paddingBottom: 90,
    backgroundColor: "#FFF",
  },
  quickActionsSectionContainer: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 24,
    minHeight: 154,
    borderWidth: 0.2,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.1)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 0,
  },
  quickActionsSection: {
    marginTop: 10,
    paddingHorizontal: 10,
  },
  serviceItem: {
    alignItems: "center",
    width: SCREEN_WIDTH / 4 - 22,
    margin: 5,
  },
  serviceIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    shadowColor: "#808080",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 3,
  },
  serviceImage: {
    width: 60,
    height: 60,
    borderRadius: 12,
    objectFit: "contain",
  },
  serviceText: {
    fontSize: 12,
    textAlign: "center",
    color: "#162329",
    fontWeight: "bold",
    fontFamily: "Inter_18pt-Bold",
  },
  overlayImage: {
    width: 60,
    height:60,
    position: "absolute",
    top: -30,
    right: -20,
    zIndex: 1,
  },
  separatorButton: {
    position: "absolute",
    alignSelf: "center",
    marginTop: 134,
    backgroundColor: "#ea2c50",
    borderRadius: 15,
    zIndex: 10,
    justifyContent: "center",
    alignItems: "center",
    width: 30,
    height: 30,
    overflow: "hidden",
  },
  gridSectionContainer: {
    paddingHorizontal: 10,
  },
  gridSection: {
    marginTop: 4,
    paddingHorizontal: 10,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#162329",
    textAlign: "left",
    marginLeft: 4,
    fontFamily: "Inter_18pt-Bold",
  },
  gridItem1: {
    alignItems: "center",
    width: SCREEN_WIDTH / 4 - 24,
    margin: 6,
  },
  gridIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 4,
    shadowColor: "#808080",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 0.3,
    borderColor: "#D3D3D3",
  },
  gridImage: {
    width: 48,
    height: 48,
    borderRadius: 10,
    objectFit: "contain",
  },
  // Sticky Styles
  stickyContainer: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    zIndex: 2000,
  },
  bottomNavContainer: {
    width: "100%",
    paddingHorizontal: 18,
    alignSelf: "center",
    marginBottom: 10,
  },
  bottomNav: {
    backgroundColor: "#354a57",
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingVertical: 6,
  },
  bottomNavItem: {
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  qrNavItem: {
    alignItems: "center",
    paddingVertical: 11,
    paddingHorizontal: 10,
    height: 60,
    justifyContent: "center",
  },
  bottomNavImage: {
    width: 40,
    height: 40,
  },
  qrNavImage: {
    width: 60,
    height: 60,
    borderRadius: 20,
  },
  bottomNavText: {
    fontSize: 11,
    color: "#FFF",
    marginTop: 0,
    fontFamily: "Inter_18pt-Bold",
  },
});