import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#f2f7fd',
    padding: 0,
  },
  homeButton: {
    position: 'absolute',
    top: 26,
    right: 20,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  homeIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  checkmarkIcon: {
    width: 180,
    height: 180,
    resizeMode: 'center',
  },
  successText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333',
    fontFamily: 'Roboto',
    textAlign: 'center',
  },
  amountText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#2f5884',
    marginTop: 8,
    fontFamily: 'Roboto',
    textAlign: 'center',
  },
  dateTimeText: {
    fontSize: 14,
    color: '#666666',
    marginTop: 8,
    fontFamily: 'Roboto',
    textAlign: 'center',
  },
  arrowDownIcon: {
    marginTop: 4,
    marginBottom: 4,
  },
  transactionBox: {
    backgroundColor: '#f9f8fe',
    borderRadius: 4,
    width: '90%',
    paddingTop: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  recipientName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1b313e',
    textAlign: 'center',
    marginBottom: 0,
    fontFamily: 'Roboto',
    textTransform: 'uppercase',
  },
  bankInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 0,
  },
  bankIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
    marginRight: 6,
  },
  bankText: {
    fontSize: 16,
    fontWeight: 'light',
    color: '#1b313e',
    fontFamily: 'Roboto',
  },
  accountNumberText: {
    fontSize: 16,
    color: '#1b313e',
    textAlign: 'center',
    marginBottom: 8,
    fontFamily: 'Roboto',
  },
  descriptionText: {
    fontSize: 14,
    color: '#1B313E',
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  transactionBoxArrowContainer: {
    alignItems: 'center',
    marginTop: 8,
  },
  transactionBoxArrow: {
    width: 28,
    height: 28,
    borderWidth: 1,
    borderColor: '#d7e2f6',
    borderRadius: 14,
    paddingHorizontal:6,
    paddingTop: 7,
    backgroundColor: '#d7e2f6',
    justifyContent: 'center',
    alignItems: 'center',
    top: 12,
  },
  thankYouText: {
    fontSize: 16,
    color: '#666666',
    marginTop: 20,
    marginBottom: 8,
    fontFamily: 'Roboto',
  },
  mbBankLogo: {
    width: 210,
    height: 60,
    resizeMode: 'contain',
    marginBottom: 0,
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '76%',
    marginBottom: 40,
  },
  actionButtonWrapper: {
    alignItems: 'center',
  },
  actionButton: {
    width: 54,
    height: 54,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionIcon: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  actionButtonText: {
    fontSize: 14,
    color: '#1B313E',
    fontFamily: 'Roboto',
    textAlign: 'center',
    marginTop: 0,
  },
  bottomButtonContainer: {
    width: '90%',
    alignItems: 'center',
  },
  applePayButtonContainer: {
    position: 'relative',
    width: '100%',
    marginBottom: 20,
  },
  applePayButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#000000',
    borderRadius: 4,
    padding: 12,
    width: '100%',
    height: 60,
  },
  applePayIcon: {
    width: 50,
    height: 26,
    resizeMode: 'cover',
    backgroundColor: 'white',
  },
  applePayButtonText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
    marginRight: 8,
  },
  discountLabel: {
    height: 24,
    position: 'absolute',
    top: -10,
    right: 0,
    backgroundColor: '#d64456',
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  discountText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  anotherTransactionButton: {
    height: 60,
    borderWidth: 1,
    borderColor: '#2f5884',
    borderRadius: 4,
    padding: 16,
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  anotherTransactionButtonText: {
    fontSize: 18,
    color: '#2f5884',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
});

export default styles;